# Generated by Django 5.2.5 on 2025-08-29 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Kapal')),
                ('registration_number', models.CharField(max_length=100, unique=True, verbose_name='Nomor Registrasi')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Panjang (meter)')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Lebar (meter)')),
                ('gross_tonnage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gross Tonnage')),
                ('year_built', models.IntegerField(blank=True, null=True, verbose_name='Tahun Dibuat')),
                ('home_port', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pelabuhan Asal')),
                ('active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ships', to='owners.owner', verbose_name='Pemilik')),
            ],
            options={
                'verbose_name': 'Kapal',
                'verbose_name_plural': 'Kapal',
            },
        ),
    ]
