# Generated by Django 5.2.5 on 2025-08-29 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0003_captain'),
        ('ships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ships', to='owners.captain', verbose_name='Nahkoda'),
        ),
    ]
