# Generated by Django 5.2.5 on 2025-08-30 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0002_ship_captain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Tahun')),
                ('quota', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Kuota (kg)')),
                ('remaining_quota', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Sisa Kuota (kg)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='ships.ship', verbose_name='Kapal')),
            ],
            options={
                'verbose_name': 'Kuota',
                'verbose_name_plural': 'Kuota',
                'unique_together': {('ship', 'year')},
            },
        ),
    ]
