# Generated by Django 5.2.6 on 2025-09-22 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0006_alter_customuser_role'),
        ('ships', '0003_quota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ships', to='owners.owner', verbose_name='Pemilik'),
        ),
    ]
