# Generated by Django 4.2.3 on 2025-05-20 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nama Nahkoda')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='Nomor Lisensi')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir')),
                ('contact_info', models.TextField(blank=True, null=True, verbose_name='Informasi Kontak')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nomor Telepon')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Alamat')),
                ('years_of_experience', models.IntegerField(blank=True, null=True, verbose_name='Tahun Pengalaman')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captains', to='owners.owner', verbose_name='Pemilik Kapal')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captain', to='owners.customuser', verbose_name='Akun Pengguna')),
            ],
            options={
                'verbose_name': 'Nahkoda',
                'verbose_name_plural': 'Nahkoda',
            },
        ),
    ]