# Generated by Django 5.2.5 on 2025-08-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0003_captain'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('owner', 'Pemilik Kapal'), ('captain', 'Nahkoda')], default='owner', max_length=20, verbose_name='Peran Pengguna'),
        ),
    ]
