# Generated by Django 5.2.5 on 2025-08-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0004_customuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='captain',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='name',
        ),
        migrations.AddField(
            model_name='owner',
            name='full_name',
            field=models.CharField(default=1, max_length=200, verbose_name='Nama Lengkap'),
            preserve_default=False,
        ),
    ]
