# Generated by Django 5.2.5 on 2025-09-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0005_rename_name_captain_full_name_remove_owner_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('regulator', 'Regulator'), ('owner', 'Pemilik Kapal'), ('captain', 'Nahkoda')], default='owner', max_length=20, verbose_name='Peran Pengguna'),
        ),
    ]
