# Generated by Django 5.2.5 on 2025-09-15 13:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainBlock',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data', models.TextField()),
                ('previous_hash', models.CharField(max_length=64)),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('nonce', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Blok Blockchain',
                'verbose_name_plural': 'Blok Blockchain',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='BlockchainConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Konfigurasi Blockchain',
                'verbose_name_plural': 'Konfigurasi Blockchain',
            },
        ),
        migrations.CreateModel(
            name='FishCatchTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ship_registration_number', models.CharField(max_length=100, verbose_name='Nomor Registrasi Kapal')),
                ('fishing_area_code', models.CharField(max_length=20, verbose_name='Kode Wilayah Penangkapan')),
                ('fish_species_code', models.CharField(max_length=100, verbose_name='Kode Jenis Ikan')),
                ('fish_name', models.CharField(max_length=100, verbose_name='Nama Ikan')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Jumlah')),
                ('unit', models.CharField(max_length=20, verbose_name='Satuan')),
                ('catch_date', models.DateField(verbose_name='Tanggal Penangkapan')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='blockchain.blockchainblock')),
            ],
            options={
                'verbose_name': 'Transaksi Blockchain Penangkapan Ikan',
                'verbose_name_plural': 'Transaksi Blockchain Penangkapan Ikan',
            },
        ),
    ]
