# Generated by Django 4.2.3 on 2025-05-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_registration_number', models.CharField(max_length=100, verbose_name='Nomor Registrasi Kapal')),
                ('fishing_area_code', models.CharField(max_length=50, verbose_name='Kode Wilayah Penangkapan')),
                ('fish_species_code', models.CharField(max_length=50, verbose_name='Kode Spesies Ikan')),
                ('fish_name', models.CharField(max_length=100, verbose_name='Nama Ikan')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jumlah')),
                ('unit', models.CharField(max_length=10, verbose_name='Satuan')),
                ('catch_date', models.DateField(verbose_name='Tanggal Penangkapan')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('blockchain_hash', models.CharField(max_length=64, unique=True, verbose_name='Hash Blockchain')),
                ('previous_hash', models.CharField(max_length=64, verbose_name='Hash Sebelumnya')),
                ('nonce', models.IntegerField(verbose_name='Nonce')),
            ],
            options={
                'verbose_name': 'Transaksi Blockchain',
                'verbose_name_plural': 'Transaksi Blockchain',
                'ordering': ['-timestamp'],
            },
        ),
    ]