# Generated by Django 5.2.5 on 2025-09-11 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ship_registration_number', models.CharField(max_length=100, verbose_name='Nomor Registrasi Kapal')),
                ('quota_amount', models.FloatField(verbose_name='Jumlah Kuota')),
                ('quota_unit', models.CharField(default='kg', max_length=20, verbose_name='Satuan Kuota')),
                ('allocation_date', models.DateField(verbose_name='Tanggal Alokasi')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_transactions', to='blockchain.blockchainblock')),
            ],
            options={
                'verbose_name': 'Transaksi Blockchain Kuota',
                'verbose_name_plural': 'Transaksi Blockchain Kuota',
            },
        ),
    ]
