# Generated by Django 5.2.5 on 2025-09-15 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blockchain', '0001_initial'),
        ('catches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishcatchtransaction',
            name='fish_catch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_transactions', to='catches.fishcatch'),
        ),
    ]
