# Generated by Django 5.2.5 on 2025-09-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_quotatransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishcatchtransaction',
            name='quota_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Jumlah Kuota'),
        ),
        migrations.AddField(
            model_name='fishcatchtransaction',
            name='quota_unit',
            field=models.CharField(default='kg', max_length=20, verbose_name='Satuan Kuota'),
        ),
        migrations.DeleteModel(
            name='QuotaTransaction',
        ),
    ]
