# Generated by Django 5.2.5 on 2025-09-15 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blockchain', '0002_initial'),
        ('ships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishcatchtransaction',
            name='quota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blockchain_transactions', to='ships.quota', verbose_name='Kuota'),
        ),
    ]
