# Generated by Django 5.2.5 on 2025-10-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishcatchtransaction',
            name='pnbp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='PNBP'),
        ),
        migrations.AddField(
            model_name='fishcatchtransaction',
            name='pnkp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='PNKP (Nilai Produksi Ikan)'),
        ),
        migrations.AddField(
            model_name='fishcatchtransaction',
            name='tarif_index',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='Tarif Index'),
        ),
    ]
