# Generated by Django 5.2.5 on 2025-09-11 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_fishcatchtransaction_quota_amount_and_more'),
        ('ships', '0003_quota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fishcatchtransaction',
            name='quota_amount',
        ),
        migrations.RemoveField(
            model_name='fishcatchtransaction',
            name='quota_unit',
        ),
        migrations.AddField(
            model_name='fishcatchtransaction',
            name='quota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blockchain_transactions', to='ships.quota', verbose_name='Kuota'),
        ),
    ]
