# Generated by Django 4.2.3 on 2025-05-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FishSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Spesies')),
                ('scientific_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Ilmiah')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('conservation_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status Konservasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Spesies Ikan',
                'verbose_name_plural': 'Spesies Ikan',
                'ordering': ['name'],
            },
        ),
    ]