# Generated by Django 5.2.5 on 2025-09-15 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fishspecies',
            options={'verbose_name': 'Jenis Ikan', 'verbose_name_plural': 'Jenis Ikan'},
        ),
        migrations.RemoveField(
            model_name='fishspecies',
            name='conservation_status',
        ),
        migrations.AlterField(
            model_name='fishspecies',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nama Ikan'),
        ),
        migrations.AlterField(
            model_name='fishspecies',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nama Ilmiah'),
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Ikan')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Berat (kg)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_fish', to='fish.fishspecies', verbose_name='Jenis Ikan')),
            ],
            options={
                'verbose_name': 'Ikan',
                'verbose_name_plural': 'Ikan',
            },
        ),
    ]
