# Generated by Django 5.2.5 on 2025-08-29 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Ikan')),
                ('gender', models.CharField(choices=[('male', 'Jantan'), ('female', 'Betina'), ('unknown', 'Tidak Diketahui')], default='unknown', max_length=10, verbose_name='Jenis Kelamin')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Panjang (cm)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Berat (kg)')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Usia (tahun)')),
                ('catch_location_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude Lokasi Penangkapan')),
                ('catch_location_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude Lokasi Penangkapan')),
                ('catch_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Penangkapan')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_fish', to='fish.fishspecies', verbose_name='Jenis Ikan')),
            ],
            options={
                'verbose_name': 'Ikan',
                'verbose_name_plural': 'Ikan',
            },
        ),
    ]
