# Generated by Django 5.2.5 on 2025-10-09 09:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0002_alter_fishspecies_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishPriceReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Harga Acuan per kg (Rp)')),
                ('effective_date', models.DateField(auto_now_add=True, verbose_name='Tanggal Efektif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('fish_species', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_reference', to='fish.fishspecies', verbose_name='Jenis Ikan')),
            ],
            options={
                'verbose_name': 'Harga Acuan Ikan',
                'verbose_name_plural': 'Harga Acuan Ikan',
                'unique_together': {('fish_species', 'effective_date')},
            },
        ),
    ]
