# Generated by Django 5.2.5 on 2025-08-30 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0002_fish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='age',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='catch_date',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='catch_location_latitude',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='catch_location_longitude',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='gender',
        ),
    ]
