# Generated by Django 5.2.5 on 2025-09-01 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0003_remove_fish_age_remove_fish_catch_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='length',
        ),
    ]
