# Generated by Django 5.2.5 on 2025-09-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Lengkap')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nomor Telepon')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departemen')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Posisi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
            ],
            options={
                'verbose_name': 'Profil Admin',
                'verbose_name_plural': 'Profil Admin',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Menu')),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name='URL')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ikon')),
                ('order', models.IntegerField(default=0, verbose_name='Urutan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nama Peran')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
            ],
            options={
                'verbose_name': 'Peran',
                'verbose_name_plural': 'Peran',
            },
        ),
        migrations.CreateModel(
            name='RoleMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True, verbose_name='Dapat Melihat')),
                ('can_create', models.BooleanField(default=False, verbose_name='Dapat Membuat')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Dapat Mengedit')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Dapat Menghapus')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Ditugaskan Pada')),
            ],
            options={
                'verbose_name': 'Menu Peran',
                'verbose_name_plural': 'Menu Peran',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Ditugaskan Pada')),
            ],
            options={
                'verbose_name': 'Peran Pengguna',
                'verbose_name_plural': 'Peran Pengguna',
            },
        ),
    ]
