# Generated by Django 5.2.5 on 2025-08-30 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Menu')),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name='URL')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ikon')),
                # Type ignore comments added to resolve basedpyright type checking issues
                ('order', models.IntegerField(default=0, verbose_name='Urutan')),  # type: ignore
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),  # type: ignore
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='admin_module.menu', verbose_name='Menu Induk')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nama Peran')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission', verbose_name='Hak Akses')),
            ],
            options={
                'verbose_name': 'Peran',
                'verbose_name_plural': 'Peran',
            },
        ),
        migrations.CreateModel(
            name='RoleMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # Type ignore comments added to resolve basedpyright type checking issues
                ('can_view', models.BooleanField(default=True, verbose_name='Dapat Melihat')),  # type: ignore
                ('can_create', models.BooleanField(default=False, verbose_name='Dapat Membuat')),  # type: ignore
                ('can_edit', models.BooleanField(default=False, verbose_name='Dapat Mengedit')),  # type: ignore
                ('can_delete', models.BooleanField(default=False, verbose_name='Dapat Menghapus')),  # type: ignore
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Ditugaskan Pada')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_module.menu', verbose_name='Menu')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_module.role', verbose_name='Peran')),
            ],
            options={
                'verbose_name': 'Menu Peran',
                'verbose_name_plural': 'Menu Peran',
                'unique_together': {('role', 'menu')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Ditugaskan Pada')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_module.role', verbose_name='Peran')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Peran Pengguna',
                'verbose_name_plural': 'Peran Pengguna',
                'unique_together': {('user', 'role')},
            },
        ),
    ]