# Generated by Django 4.2.3 on 2025-05-20 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_customuser'),
        ('admin_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nama Lengkap')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telepon')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departemen')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Posisi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to='owners.customuser', verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Profil Admin',
                'verbose_name_plural': 'Profil Admin',
            },
        ),
    ]