# Generated by Django 5.2.5 on 2025-08-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FishingArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Wilayah')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('boundary_coordinates', models.TextField(blank=True, null=True, verbose_name='Koordinat Batas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wilayah Penangkapan',
                'verbose_name_plural': 'Wilayah Penangkapan',
            },
        ),
    ]
