# Generated by Django 5.2.5 on 2025-08-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishingarea',
            name='code',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='Kode Wilayah'),
            preserve_default=False,
        ),
    ]
