# Generated by Django 5.2.5 on 2025-09-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fishingarea',
            options={'verbose_name': 'Wilayah Penangkapan', 'verbose_name_plural': 'Wilayah Penangkapan'},
        ),
        migrations.AlterField(
            model_name='fishingarea',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Kode Wilayah'),
        ),
    ]
