# Generated by Django 5.2.5 on 2025-08-31 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_fishingarea_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fishingarea',
            old_name='name',
            new_name='nama',
        ),
        migrations.RemoveField(
            model_name='fishingarea',
            name='boundary_coordinates',
        ),
    ]
