# Generated by Django 5.2.5 on 2025-09-01 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_rename_name_fishingarea_nama_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fishingarea',
            old_name='description',
            new_name='deskripsi',
        ),
    ]
