# Generated by Django 5.2.5 on 2025-08-29 14:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fish', '0001_initial'),
        ('ships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishCatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catch_date', models.DateField(verbose_name='Tanggal Penangkapan')),
                ('catch_type', models.CharField(choices=[('pelagic', 'Pelagis'), ('demersal', 'Demersal'), ('reef', 'Terumbu Karang')], max_length=20, verbose_name='Jenis Penangkapan')),
                ('location_latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude Lokasi')),
                ('location_longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude Lokasi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catch_reports', to='ships.ship', verbose_name='Kapal')),
            ],
            options={
                'verbose_name': 'Penangkapan Ikan',
                'verbose_name_plural': 'Penangkapan Ikan',
            },
        ),
        migrations.CreateModel(
            name='CatchDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Jumlah')),
                ('unit', models.CharField(default='kg', max_length=20, verbose_name='Satuan')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Nilai')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('fish_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish.fishspecies', verbose_name='Jenis Ikan')),
                ('fish_catch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catch_details', to='catches.fishcatch', verbose_name='Laporan Penangkapan')),
            ],
            options={
                'verbose_name': 'Detail Penangkapan',
                'verbose_name_plural': 'Detail Penangkapan',
            },
        ),
    ]
