# Generated by Django 4.2.3 on 2025-05-20 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fish', '0001_initial'),
        ('owners', '0002_customuser'),
        ('ships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishCatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catch_date', models.DateField(verbose_name='Tanggal Penangkapan')),
                ('location', models.CharField(max_length=200, verbose_name='Lokasi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catch_reports', to='owners.customuser', verbose_name='Pelapor')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catches', to='ships.ship', verbose_name='Kapal')),
            ],
            options={
                'verbose_name': 'Tangkapan Ikan',
                'verbose_name_plural': 'Tangkapan Ikan',
                'ordering': ['-catch_date'],
            },
        ),
        migrations.CreateModel(
            name='CatchDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jumlah')),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('ton', 'Ton'), ('ekor', 'Ekor')], max_length=10, verbose_name='Satuan')),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Nilai Perkiraan')),
                ('fish_catch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='catches.fishcatch', verbose_name='Tangkapan Ikan')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish.fishspecies', verbose_name='Spesies')),
            ],
            options={
                'verbose_name': 'Detail Tangkapan',
                'verbose_name_plural': 'Detail Tangkapan',
            },
        ),
    ]