# Generated by Django 5.2.5 on 2025-09-22 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0001_initial'),
        ('regions', '0002_alter_fishingarea_options_alter_fishingarea_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='catchdetail',
            name='wpp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.fishingarea', verbose_name='WPP'),
        ),
    ]
