# Generated by Django 5.2.5 on 2025-09-15 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catches', '0001_initial'),
        ('ships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishcatch',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catch_reports', to='ships.ship', verbose_name='Kapal'),
        ),
        migrations.AddField(
            model_name='catchdetail',
            name='fish_catch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catch_details', to='catches.fishcatch', verbose_name='Laporan Penangkapan'),
        ),
    ]
