# Generated by Django 5.2.5 on 2025-09-26 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0002_catchdetail_wpp'),
        ('catches', '0002_initial'),
    ]

    operations = [
    ]
