# Generated by Django 5.2.5 on 2025-10-09 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catches', '0003_merge_0002_catchdetail_wpp_0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nama Tarif')),
                ('gt_threshold', models.DecimalField(decimal_places=2, default=60, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Batas GT')),
                ('rate_small', models.DecimalField(decimal_places=4, default=0.05, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tarif GT Kecil (%)')),
                ('rate_large', models.DecimalField(decimal_places=4, default=0.1, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tarif GT Besar (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('effective_date', models.DateField(auto_now_add=True, verbose_name='Tanggal Efektif')),
            ],
            options={
                'verbose_name': 'Tarif PNBP',
                'verbose_name_plural': 'Tarif PNBP',
            },
        ),
        migrations.AddField(
            model_name='catchdetail',
            name='pnbp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='PNBP'),
        ),
        migrations.AddField(
            model_name='catchdetail',
            name='pnkp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='PNKP (Nilai Produksi Ikan)'),
        ),
        migrations.AddField(
            model_name='catchdetail',
            name='tarif_index',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='Tarif Index'),
        ),
    ]
